### ISSUE TITLE
Toggle functionality 

### ISSUE THREAD

**Issue by kdichev** [zwug/react-full-page#11]
As most of the scrolling is controlled by the package there should be a way of pausing/stopping the functions that are attached to the different events and return control of the scroll to the browser.

When opening a dialog on the page scrolling still happens on the background. 
This also probably disables the functionality of any scrollable content that one might want to have.

My solution for now is to expose a boolean prop to the component which stops onScroll before it gets preventDefaulted.

**Comment by zwug** [comment]
https://github.com/zwug/react-full-page/releases/tag/0.1.5 released

**Comment by sajumani** [comment]
@zwug 0.1.5  Not what we needed exactly ...

We should have an option to lock particular Slide. Scroll to next Or Control want to disable by default
