### ISSUE TITLE
Routing inside scroller

### ISSUE THREAD

**Issue by dropsydice** [zwug/react-full-page#12]
Can I, somehow, add route path for each slide?

**Comment by zwug** [comment]
Do you mean something like myapp.com/fullpage#slide1, myapp.com/fullpage#slide2 ?

**Comment by dropsydice** [comment]
Yes, exactly! I have spent two day for this, but i'm novice, so my attempt to do it with react-router have failed, i'll be happy if you help me)

**Comment by zwug** [comment]
Why can't you use hash in your routes? I think using hash is the only right way to bind route and scrolling.
And I think that this feature should work regardless of the react-router presence. A quick research gave me [this](https://github.com/alvarotrigo/fullPage.js/blob/3e33e653f579ad7f6ba927af3bb6aeb4881a436e/pure%20javascript%20(Alpha)/javascript.fullPage.js#L301).
Tell me if you have other questions 😉

**Comment by dropsydice** [comment]
Thank you a lot for help, you are saving me! 
But how can i bind a URL route like "app.com/photo" to a Slide? And could i go then to a chosen Slide by typing a URL address of this Slide in browser?

My app looks like a long scroll page and it has critical needs the ability to give somebody a link just for specific slide.

render() {
    return (
      <FullPage>
        <Slide><About/></Slide> 
        <Slide><Programs/></Slide>
        <Slide><Photo/></Slide> /*How can i scroll here
      </FullPage>
    );
  }

**Comment by zwug** [comment]
In that case you need to implement this functionality by yourself, because it is not a common behaviour. You can parse route somewhere before render, determine the desired slide index and then call `scrollToSlide` method of `FullPage` using React refs

**Comment by dropsydice** [comment]
Thank you! I will try this!
