### ISSUE TITLE
Add custom controls

### ISSUE THREAD

**Issue by ppsirius** [zwug/react-full-page#13]
How can I add custom controls?

**Comment by zwug** [comment]
You create your own controls component and pass it to the `controls` prop of `FullPage`.

**Comment by ppsirius** [comment]
Have you an example of this?

**Comment by ppsirius** [comment]
I get error when try to add CustomControls.
`Warning: Failed prop type: Invalid prop `controls` supplied to `FullPage`.`

**Comment by zwug** [comment]
Yes, I checked it and this error appeared in my project because of the babel transpiling, I guess. I will fix this.

**Comment by zwug** [comment]
Fixed [here](https://github.com/zwug/react-full-page/commit/0f3b76a73afb1c6d8e2ab5ac229c20668d6764dd)

**Comment by ppsirius** [comment]
How I can access to getCurrentSlideIndex on my Custom Controls and how can I scrollToSlide?

**Comment by zwug** [comment]
Looks like another bug 😞 . I will fix it later today

**Comment by zwug** [comment]
Fixed [here](https://github.com/zwug/react-full-page/commit/4ddad57fc9df01250fda6c16277b8371065b0a8d)
