### ISSUE TITLE
mobile devices disable scroll

### ISSUE THREAD

**Issue by goodok21** [zwug/react-full-page#20]
How to disable scrolling to next slide while using it on the mobile?

**Comment by zwug** [comment]
If you mean enabling/disabling full page scrolling depending on the width of viewport or user-agent - there is no convenient way for that now. But the resolving of [this](https://github.com/zwug/react-full-page/issues/11) issue will help to solve your problem. I'll look into it.

**Comment by goodok21** [comment]
Can you show the code example to disable full page scrolling? Btw, did anyone trying to open the demo in iOS Safari? How to solve problems with scrolling?

**Comment by zwug** [comment]
Disabling full page scrolling and using default scroll is "work in progress" for now. Right now there is no convenient way to disable it.

**Comment by zwug** [comment]
https://github.com/zwug/react-full-page/pull/22 brings a prop to resolve this

**Comment by zwug** [comment]
https://github.com/zwug/react-full-page/releases/tag/0.1.5 released
