### ISSUE TITLE
when the slide component is set as height:auto, cant scroll down smoothly

### ISSUE THREAD

**Issue by ffan0811** [zwug/react-full-page#25]
Let's say I have 3 sections which are set as height:100% which is default set from the react-full-page. and 1 footer.

It scrolls down well till the last section However, when its scrolling down from the 3rd section to the footer which is set as height:auto by me since I don't want it to be 100%, It seems like It doesn't scroll down smoothly. but When I scroll up from the footer to the 3rd section, it scrolls up smoothly.

Is there any idea why its like this??

thank you.

**Comment by zwug** [comment]
Can you provide the code, that I could reproduce this behaviour?
