### ISSUE TITLE
Scroll not working for ie11

### ISSUE THREAD

**Issue by yarron** [zwug/react-full-page#30]
Hello.
In ie11 your library does not work. There are no errors, but when scrolling or during the transition, the page always seeks to the top

**Comment by zwug** [comment]
Thanks, the fix is coming #31.
The problem was in `window.scrollY`

**Comment by zwug** [comment]
Check out http://zwug.github.io/react-full-page/. Should be working now 🙂

**Comment by yarron** [comment]
> Check out http://zwug.github.io/react-full-page/. Should be working now
Thanks, it works
