### ISSUE TITLE
Module not found: Can't resolve 'core-js/modules/es6.array.iterator'

### ISSUE THREAD

**Issue by sabirahmed121** [zwug/react-full-page#38]
Trying to use the library in a CRA (Create React App)

Failed to compile.

./node_modules/react-full-page/lib/components/Slide.js
Module not found: Can't resolve 'core-js/modules/es6.array.iterator' in 'landing-1/node_modules/react-full-page/lib/components'

Version : 0.1.8

**Comment by futpib** [comment]
@sabirahmed121 Did you solve it?

**Comment by zwug** [comment]
Seems like this problem doesn't occur if you use the module as an npm library, but when you work this repository only

**Comment by z1m1n** [comment]
@zwug I got this issue too. Can you please release fix?

**Comment by zwug** [comment]
@z1m1n the latest version seems to be fine. Could you please provide more info? The library version, node version, OS?

**Comment by staff0rd** [comment]
Occurred for me after `yarn add react-full-page`.

I had to install `core-js` as suggested above.

```json
"dependencies": {
    "@material-ui/core": "^4.11.0",
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.3.2",
    "@testing-library/user-event": "^7.1.2",
    "core-js": "2",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-full-page": "^0.1.9",
    "react-scripts": "3.4.1"
  },
```

npm v10.14.1

**Comment by zwug** [comment]
Thanks, I found the issue when I tried to use the library with CRA.
