### ISSUE TITLE
Can't change _slidesCount when fetching new data

### ISSUE THREAD

**Issue by Extnow** [zwug/react-full-page#39]
Hey, thanks for a good tool

Can you please explain one thing: when I initialize app, component FullPage contain 2 children, then I fetch new data and in FullPage becomes 4 children, but variable _slidesCount doesn't change. Even if I pass slidesCount manually depending on the size of the children inside, _slidesCount doesn't change.  How can I fix this? Thank you.

**Comment by Extnow** [comment]
What about add this code in componentDidUpdate?

```
componentDidUpdate(prevProps) {
    if (this.props.children.length !== prevProps.children.length) {
      this._slidesCount = this.props.children.length;
      this._slides = [];

      for (let i = 0; i < this._slidesCount; i++) {
        this._slides.push(window.innerHeight * i);
      }
    }
  }
```

**Comment by jnorris441** [comment]
For this situation I extended FullPage and used the new component instead.

```
class FullPageNew extends FullPage {
	componentDidUpdate(prevProps) {
	    if (this.props.children.length !== prevProps.children.length) {
	      this._slidesCount = this.props.children.length;
	      this._slides = [];

	      for (let i = 0; i < this._slidesCount; i++) {
	        this._slides.push(window.innerHeight * i);
	      }
	    }
  	}
}
```

**Comment by zwug** [comment]
Thanks, I'll fix that
