### ISSUE TITLE
Scroll is triggered on continious touch on mobile

### ISSUE THREAD

**Issue by kdichev** [zwug/react-full-page#5]
If I press and hold to slide to 2 after the scroll another scroll event will be triggered and scroll to slide 3.
Is this intended?

**Comment by zwug** [comment]
Thanks, fixed it in https://github.com/zwug/react-full-page/commit/34184ea9983dfe0d197bec4111d4a81e6c2e3655

**Comment by kdichev** [comment]
@zwug same thing is happening with touch pad both on macOS and Windows machines
